---

    - name: Ensure hostname set
      hostname: 
        name: '{{ inventory_hostname }}'

    - name: Agregar FQDN Server en /etc/hosts
      lineinfile:
        path: /etc/hosts 
        line: '{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}'
        state: present
        backup: yes