---

    - name: Configurar el hostname
      hostname: 
        name: '{{ inventory_hostname }}'

    - name: Agregar FQDN Server en /etc/hosts
      lineinfile:
        path: /etc/hosts 
        line: '10.0.2.15 {{ ansible_fqdn }} {{ ansible_hostname }}'
        state: present
        backup: yes