---

    - name: restart cockpit
      service:
        name: cockpit
        state: restarted
        enabled: yes

    - name: restart cockpit.socket
      service:
        name: cockpit.socket
        state: restarted
        enabled: yes