---

    - name: start firewalld
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: enable ssh
      firewalld:
        service: ssh
        permanent: True
        immediate: True
        state: enabled
      notify:
       - restart firewalld

    - name: enable http
      firewalld:
        service: http
        permanent: True
        immediate: True
        state: enabled
      notify:
       - restart firewalld

    - name: enable https
      firewalld:
        service: https
        permanent: True
        immediate: True
        state: enabled
      notify:
       - restart firewalld