---

    - name: start firewalld
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: enable services
      firewalld:
        service: '{{ item.key }}'
        state: '{{ item.value }}'
        permanent: True
        immediate: True
      with_dict: '{{ firewalld_services }}'
      notify:
       - restart firewalld